# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "37e49e51914544bf83dcf74502684490"
application_url = "https://remix-app-88og.onrender.com"
embedded = true
name = "remix-app-form"
handle = "remix-app-form"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,write_files,read_files,read_themes,write_themes"

[auth]
redirect_urls = [
  "https://remix-app-88og.onrender.com/auth/callback",
  "https://remix-app-88og.onrender.com/auth/shopify/callback",
  "https://remix-app-88og.onrender.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "trevorf-testing.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
